# Generated by Django 4.1.4 on 2022-12-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_name', models.CharField(max_length=200)),
                ('peak_coordinates', models.IntegerField(default=0)),
                ('peak_height', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=200)),
                ('peak_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
